# Generated by Django 6.0.3 on 2026-03-06 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='downloadable_file',
            field=models.FileField(blank=True, help_text='PDF or document for farmers to download', null=True, upload_to='articles/downloads/'),
        ),
        migrations.AddField(
            model_name='article',
            name='file_description',
            field=models.CharField(blank=True, help_text="E.g., 'Complete Maize Guide (PDF, 2.5MB)'", max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Full article content. You can use HTML for formatting.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
        migrations.CreateModel(
            name='ArticleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1 - Not Helpful'), (2, '2 - Somewhat Helpful'), (3, '3 - Helpful'), (4, '4 - Very Helpful'), (5, '5 - Extremely Helpful')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='knowledge.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('article', 'user')},
            },
        ),
    ]
