"""Context processors for Nhimbe AI"""

TRANSLATIONS = {
    'en': {
        'home': 'Home',
        'forum': 'Forum',
        'knowledge': 'Knowledge',
        'about': 'About',
        'profile': 'Profile',
        'login': 'Login',
        'logout': 'Logout',
        'register': 'Register',
        'search': 'Search',
        'new_post': 'New Post',
        'welcome': 'Welcome',
        'join': 'Join the Community',
        'learn_more': 'Learn More',
        'hero_title': 'Farming Wisdom, Powered by Community and AI',
        'hero_subtitle': 'Get instant agricultural advice, connect with fellow farmers, and grow smarter. Grounded in local knowledge, designed for Zimbabwean smallholders.',
        'how_helps': 'How Nhimbe AI Helps You',
        'tools_community': 'Tools and community designed for Zimbabwean farmers',
        'ask_ai': 'Ask AI Assistant',
        'ai_chat': 'AI Chat',
        'visit_forum': 'Visit Forum',
        'post_comment': 'Post Comment',
        'leave_comment': 'Leave a Comment',
        'no_posts': 'No discussions yet. Be the first to start one.',
        'no_comments': 'No comments yet. Share your thoughts below.',
        'login_to_comment': 'Login to join the discussion.',
        'save_changes': 'Save Changes',
        'update_profile': 'Update Profile',
        'create_account': 'Create Account',
        'conversations': 'Conversations',
        'new_chat': 'New Chat',
        'clear_chat': 'Clear chat',
        'ask_farming': 'Ask about farming...',
        'chat_welcome_title': 'Nhimbe AI Assistant',
        'chat_welcome_text': 'Ask me anything about farming in Zimbabwe. I can help with crops, livestock, soil, weather, and more.',
        'knowledge_base': 'Knowledge Base',
        'knowledge_subtitle': 'Curated farming guides for Zimbabwean conditions',
        'search_articles': 'Search articles...',
        'featured': 'Featured',
        'browse_topic': 'Browse by Topic',
        'recent_articles': 'Recent Articles',
        'was_helpful': 'Was this article helpful?',
        'login_to_rate': 'Log in to rate this article.',
        'download_resource': 'Download Resource',
        'download': 'Download',
        'related_articles': 'Related Articles',
        'views': 'views',
        'view': 'view',
        'ago': 'ago',
        'manage_articles': 'Manage Articles',
        'create_article': 'Create Article',
        'edit_article': 'Edit Article',
        'delete_article': 'Delete Article',
        'basic_info': 'Basic Information',
        'author_info': 'Author Information',
        'who_wrote': 'Who wrote this article?',
        'i_wrote': 'I wrote this article',
        'external_source': 'External source (FAO, AGRITEX, etc.)',
        'article_content': 'Article Content',
        'media_downloads': 'Media & Downloads',
        'publishing_options': 'Publishing Options',
        'publish_now': 'Publish immediately',
        'feature_homepage': 'Feature on homepage',
        'cancel': 'Cancel',
        'delete_confirm': 'This action cannot be undone.',
        'yes_delete': 'Yes, Delete Article',
        'view_source': 'View Original Source',
        'edit': 'Edit',
        'delete': 'Delete',
        'published': 'Published',
        'draft': 'Draft',
        'footer_tagline': 'Empowering Zimbabwean farmers through AI and community',
    },
    'sn': {
        'home': 'Kumba',
        'forum': 'Dare',
        'knowledge': 'Ruzivo',
        'about': 'Nezvatauri',
        'profile': 'Tsanangudzo',
        'login': 'Pinda',
        'logout': 'Buda',
        'register': 'Nyoresa',
        'search': 'Tsvaga',
        'new_post': 'Nyaya Itsva',
        'welcome': 'Mauya',
        'join': 'Batai Nesu',
        'learn_more': 'Dzidza Zvimwe',
        'hero_title': 'Huchenjeri Hwekurima, Hunotsigirwa Nevanhu neAI',
        'hero_subtitle': 'Wana mazano ekurima nekukurumidza, batana nevamwe varimi, uye kurima zviri nani. Zvakavakirwa paruzivo rwemuno, zvakagadzirirwa varimi veZimbabwe.',
        'how_helps': 'Nhimbe AI Inokubatsira Sei',
        'tools_community': 'Maturusi nevanhu vakagadzirirwa varimi veZimbabwe',
        'ask_ai': 'Bvunza AI',
        'ai_chat': 'Taura neAI',
        'visit_forum': 'Enda kuDare',
        'post_comment': 'Tumira Maonero',
        'leave_comment': 'Siya Maonero',
        'no_posts': 'Hapana nhaurirano dziripo. Iva wekutanga kutanga imwe.',
        'no_comments': 'Hapana maonero. Govana pfungwa dzako pasi apa.',
        'login_to_comment': 'Pinda kuti upinde munhaurirano.',
        'save_changes': 'Chengetedza',
        'update_profile': 'Gadziridza Tsanangudzo',
        'create_account': 'Gadzira Akaundi',
        'conversations': 'Nhaurirano',
        'new_chat': 'Nhaurirano Itsva',
        'clear_chat': 'Dzima nhaurirano',
        'ask_farming': 'Bvunza nezvekurima...',
        'chat_welcome_title': 'Nhimbe AI Mubatsiri',
        'chat_welcome_text': 'Ndibvunzei chero chinhu pamusoro pekurima muZimbabwe. Ndinogona kubatsira nezvezvirimwa, zvipfuwo, ivhu, mamiriro ekunze, nezvimwe.',
        'knowledge_base': 'Ruzivo Rwekurima',
        'knowledge_subtitle': 'Mabhuku ekurima akagadzirirwa mamiriro eZimbabwe',
        'search_articles': 'Tsvaga zvinyorwa...',
        'featured': 'Zvakanakisa',
        'browse_topic': 'Tarisa Nenyaya',
        'recent_articles': 'Zvinyorwa Zvitsva',
        'was_helpful': 'Chinyorwa ichi chabatsira here?',
        'login_to_rate': 'Pinda kuti upe maonero.',
        'download_resource': 'Dhawunirodha Rubatsiro',
        'download': 'Dhawunirodha',
        'related_articles': 'Zvinyorwa Zvakafanana',
        'views': 'maonero',
        'view': 'maonero',
        'ago': 'yapfuura',
        'manage_articles': 'Gadzirisa Zvinyorwa',
        'create_article': 'Gadzira Chinyorwa',
        'edit_article': 'Gadziridza Chinyorwa',
        'delete_article': 'Bvisa Chinyorwa',
        'basic_info': 'Ruzivo Rwekutanga',
        'author_info': 'Ruzivo Rwemunyori',
        'who_wrote': 'Ndiani akanyora chinyorwa ichi?',
        'i_wrote': 'Ndini ndakanyora',
        'external_source': 'Kubva kunze (FAO, AGRITEX, nezvimwe)',
        'article_content': 'Zviri Muchinyorwa',
        'media_downloads': 'Mifananidzo neMadhawunirodhi',
        'publishing_options': 'Sarudzo Dzekuburitsa',
        'publish_now': 'Buritsa iye zvino',
        'feature_homepage': 'Ratidza papheji rekutanga',
        'cancel': 'Kanzura',
        'delete_confirm': 'Izvi hazvinogoneki kudzoserwa.',
        'yes_delete': 'Hongu, Bvisa Chinyorwa',
        'view_source': 'Ona Kwakabva',
        'edit': 'Gadziridza',
        'delete': 'Bvisa',
        'published': 'Yakaburitswa',
        'draft': 'Dhirafiti',
        'footer_tagline': 'Kusimbisa varimi veZimbabwe kuburikidza neAI nevanhu',
    },
    'nd': {
        'home': 'Ekhaya',
        'forum': 'Inkundla',
        'knowledge': 'Ulwazi',
        'about': 'Mayelana',
        'profile': 'Isilinganiso',
        'login': 'Ngena',
        'logout': 'Phuma',
        'register': 'Bhalisa',
        'search': 'Dinga',
        'new_post': 'Udaba Olutsha',
        'welcome': 'Siyalemukela',
        'join': 'Hlanganyela Lathi',
        'learn_more': 'Funda Okwengeziwe',
        'hero_title': 'Inhlakanipho Yokulima, Eqhutshwa Ngabantu le-AI',
        'hero_subtitle': 'Thola amacebo okulima masinyane, xhumana labalimi abafowenu, njalo ulime ngcono. Kwakhiwe phezu kolwazi lwendawo, kwenzelwe abalimi abasafufusa beZimbabwe.',
        'how_helps': 'I-Nhimbe AI Ikunceda Njani',
        'tools_community': 'Amathuluzi labantu abakhelwe abalimi beZimbabwe',
        'ask_ai': 'Buza i-AI',
        'ai_chat': 'Xoxa le-AI',
        'visit_forum': 'Yana eNkundleni',
        'post_comment': 'Thumela Umbono',
        'leave_comment': 'Tshiya Umbono',
        'no_posts': 'Akulangxoxo okwamanje. Yiba ngowokuqala ukuqalisa enye.',
        'no_comments': 'Akulambono okwamanje. Yabelana imibono yakho ngaphansi.',
        'login_to_comment': 'Ngena ukuze ungene engxoxweni.',
        'save_changes': 'Gcina Ushintsho',
        'update_profile': 'Vuselela Isilinganiso',
        'create_account': 'Dala i-Akhawunti',
        'conversations': 'Izingxoxo',
        'new_chat': 'Ingxoxo Entsha',
        'clear_chat': 'Sula ingxoxo',
        'ask_farming': 'Buza ngokulima...',
        'chat_welcome_title': 'Nhimbe AI Umsizi',
        'chat_welcome_text': 'Ngibuze loba yini mayelana lokulima eZimbabwe. Nginganceda ngezilimo, izifuyo, umhlabathi, isimo sezulu, lokunye.',
        'knowledge_base': 'Ulwazi Lokulima',
        'knowledge_subtitle': 'Amabhuku okulima enzelwe isimo seZimbabwe',
        'search_articles': 'Dinga amabhuku...',
        'featured': 'Okukhethiweyo',
        'browse_topic': 'Bheka Ngesihloko',
        'recent_articles': 'Amabhuku Amatsha',
        'was_helpful': 'Ibhuku leli lisize yini?',
        'login_to_rate': 'Ngena ukuze unike umbono.',
        'download_resource': 'Dawuniloda Usizo',
        'download': 'Dawuniloda',
        'related_articles': 'Amabhuku Afananayo',
        'views': 'ukubonwa',
        'view': 'ukubonwa',
        'ago': 'edlulileyo',
        'manage_articles': 'Phatha Amabhuku',
        'create_article': 'Dala Ibhuku',
        'edit_article': 'Lungisa Ibhuku',
        'delete_article': 'Susa Ibhuku',
        'basic_info': 'Ulwazi Lokuqala',
        'author_info': 'Ulwazi Lombhali',
        'who_wrote': 'Ngubani owabhala ibhuku leli?',
        'i_wrote': 'Yimi engibhalileyo',
        'external_source': 'Okuvela ngaphandle (FAO, AGRITEX, njll.)',
        'article_content': 'Okuqukethwe Yibhuku',
        'media_downloads': 'Imifanekiso lamaDawunilodi',
        'publishing_options': 'Ukukhetha Kokuphrinta',
        'publish_now': 'Phrinta khathesi',
        'feature_homepage': 'Bonisa ekhasini lokuqala',
        'cancel': 'Susa',
        'delete_confirm': 'Lokhu akusenzelwa ukubuyiswa.',
        'yes_delete': 'Yebo, Susa Ibhuku',
        'view_source': 'Bona Okwasekuqaleni',
        'edit': 'Lungisa',
        'delete': 'Susa',
        'published': 'Kuphrinthiwe',
        'draft': 'Idhrafithi',
        'footer_tagline': 'Ukuqinisa abalimi beZimbabwe nge-AI labantu',
    },
}


def language_context(request):
    """Add user's language translations to every template"""
    lang = 'en'
    if request.user.is_authenticated and hasattr(request.user, 'preferred_language'):
        lang = request.user.preferred_language or 'en'

    return {
        'lang': lang,
        'ui': TRANSLATIONS.get(lang, TRANSLATIONS['en']),
    }